service: aws-nodejs

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: eu-west-2

functions:
  main:
    handler: handler.main
    events:
      - http:
          path: time-to-read
          method: post
          cors: true